import {
  nodes as original,
  domains as originalDomains,
  sources as originalSources,
  paths,
  recipes,
} from "./data.js";
import {
  expansionSources,
  expandUniverse,
  expansionRelations,
} from "./universe-expansion.js";
export { paths, recipes };
export const reviewed = "2026-09-13";
export const sources = {
  ...originalSources,
  ...expansionSources,
  rlTree: [
    "RL 算法分类 · Spinning Up",
    "https://spinningup.openai.com/en/latest/spinningup/rl_intro2.html",
  ],
  supervisedGuide: [
    "监督学习 · scikit-learn",
    "https://scikit-learn.org/stable/supervised_learning.html",
  ],
  unsupervisedGuide: [
    "无监督学习 · scikit-learn",
    "https://scikit-learn.org/stable/unsupervised_learning.html",
  ],
  optim: [
    "优化器与调度 · PyTorch",
    "https://docs.pytorch.org/docs/stable/optim.html",
  ],
  umap: ["UMAP · 官方文档", "https://umap-learn.readthedocs.io/en/latest/"],
  pythonGuide: [
    "Python · 官方教程",
    "https://docs.python.org/zh-cn/3/tutorial/",
  ],
};
const palette = [
  "#71dcb2",
  "#efbe77",
  "#72bcff",
  "#b6a0ff",
  "#83d5c8",
  "#ffab86",
  "#e6a0d8",
  "#a4b9d6",
];
export const domains = originalDomains.map((d, i) => ({
  ...d,
  color: palette[i],
}));
const catalog = new Map(
  original.map((n) => [n.id, { ...n, related: [...n.related] }]),
);
function add(id, title, what, when, avoid, example, source = "sklearn") {
  if (catalog.has(id)) throw Error("Duplicate " + id);
  catalog.set(id, {
    id,
    title,
    what,
    when,
    avoid,
    example,
    sources: source.split(","),
    priority: "按需",
    related: [],
    reviewed,
  });
  return id;
}
// 新叶节点写出真正的适用条件，而非用占位正文填充知识树。
const rows = [
  [
    "python-syntax",
    "变量、容器与控制流",
    "用变量、列表、字典、条件与循环组织程序。",
    "开始读写数据分析代码时。",
    "先看数据类型，不要依赖隐式类型转换。",
    "用字典统计各类别出现次数。",
    "pythonGuide",
  ],
  [
    "functions",
    "函数与模块",
    "把可重复步骤封装成独立函数与模块。",
    "清洗和特征步骤开始重复时。",
    "函数隐藏修改全局数据会妨碍排查。",
    "封装一个只依赖输入表的清洗函数。",
    "pythonGuide",
  ],
  [
    "sql-join",
    "JOIN 与聚合",
    "连接表格并按分组生成统计。",
    "组合订单、商品与用户数据。",
    "先检查连接键唯一性，避免行数膨胀。",
    "按用户汇总订单金额。",
    "sql",
  ],
  [
    "sql-window",
    "窗口函数",
    "在保留每行的同时计算排名、累计和前后值。",
    "留存、排序、滚动统计和事件间隔。",
    "分区与排序字段必须符合业务时间。",
    "用 LAG 得到用户上次购买时间。",
    "sql",
  ],
  [
    "bayes",
    "条件概率与贝叶斯",
    "根据新证据更新对事件的判断。",
    "理解概率预测与诊断证据。",
    "不要把 P(A|B) 当作 P(B|A)。",
    "结合基准发生率解释检测结果。",
    "stats",
  ],
  [
    "distributions",
    "常见概率分布",
    "二项、正态、泊松等描述不同随机过程。",
    "选择统计模型或理解数据波动。",
    "不能仅凭图形像正态就忽略生成机制。",
    "用二项分布理解转化人数。",
    "stats",
  ],
  [
    "matrix",
    "向量、矩阵与内积",
    "线性代数中表示数据和变换的基础。",
    "理解线性模型和向量相似度。",
    "计算内积前确认维度与尺度。",
    "将样本特征排列为设计矩阵。",
    "d2l",
  ],
  [
    "eigen",
    "特征值与奇异值分解",
    "把线性变换或矩阵拆成易分析的方向与尺度。",
    "理解 PCA、低秩近似。",
    "截断信息后需要检查下游损失。",
    "用 SVD 保留主要变化方向。",
    "d2l",
  ],
  [
    "power",
    "样本量与检验功效",
    "估计在给定噪声下发现有意义效果需要多少数据。",
    "设计实验周期和最小可检测效果。",
    "样本不足时不显著不代表没有效果。",
    "根据基线转化率设计实验样本量。",
    "stats",
  ],
  [
    "hypothesis",
    "假设检验",
    "在零假设下判断观察结果是否罕见。",
    "比较均值、比例或分布。",
    "p 值不是零假设成立概率；同时考虑效果量。",
    "检查转化差异并报告置信区间。",
    "stats",
  ],
  [
    "dag",
    "因果图 DAG",
    "用有向无环图表达因果假设。",
    "选择控制变量、辨认混杂与碰撞点。",
    "画出的箭头本身不构成证据。",
    "区分共同原因与干预后的中介变量。",
    "causal",
  ],
  [
    "matching",
    "匹配与倾向评分",
    "根据观测协变量让不同处理组更可比。",
    "观测研究且混杂变量被充分测量。",
    "不能消除未观测混杂。",
    "匹配背景类似的参与与未参与用户。",
    "causal",
  ],
  [
    "instrument",
    "工具变量 IV",
    "利用影响处理但满足排除等条件的外部变化识别效果。",
    "存在可信工具变量。",
    "弱工具和排除限制失败会让结论失效。",
    "先论证工具变量的相关性和识别假设。",
    "causal",
  ],
  [
    "rdd",
    "断点回归 RDD",
    "利用处理分配阈值附近的可比样本。",
    "有明确阈值且无法精确操纵分配。",
    "局部效果不能直接推广到所有人。",
    "比较资格分数阈值附近的结果。",
    "causal",
  ],
  [
    "binary",
    "二分类",
    "每个样本属于两个类别之一。",
    "流失、欺诈、是否点击。",
    "类别比例与错判代价影响评估。",
    "用逻辑回归做流失基线。",
    "supervisedGuide",
  ],
  [
    "multiclass",
    "多分类",
    "每个样本属于多个互斥类别中的一个。",
    "商品类别或手写数字识别。",
    "别与一个样本可有多个标签混淆。",
    "将图片分为猫、狗、鸟。",
    "supervisedGuide",
  ],
  [
    "multilabel",
    "多标签分类",
    "每个样本可同时拥有多个标签。",
    "文章主题或图像内容标注。",
    "不要直接当互斥 softmax 分类。",
    "一篇文章同时标记科技和金融。",
    "supervisedGuide",
  ],
  [
    "point-regression",
    "点预测回归",
    "为连续目标给出一个预测值。",
    "预测价格、时长、销量。",
    "均值预测与中位数预测的损失不同。",
    "用平方损失预测条件均值。",
    "supervisedGuide",
  ],
  [
    "quantile",
    "分位数回归",
    "预测目标的条件分位数。",
    "不对称成本或需要预测上下界。",
    "预测区间不自动具备保形覆盖保证。",
    "预测需求的 90% 分位数准备库存。",
    "supervisedGuide",
  ],
  [
    "kmeans-method",
    "K-means",
    "用 K 个中心按平方距离划分样本。",
    "有数值特征、期望较紧凑的群体。",
    "需要选 K，对尺度和离群点敏感。",
    "标准化后进行用户行为聚类。",
    "unsupervisedGuide",
  ],
  [
    "dbscan",
    "DBSCAN / HDBSCAN",
    "根据密度寻找簇，并识别噪声点。",
    "簇非球形或需要发现噪声。",
    "高维距离和密度差异会影响效果。",
    "发现地理位置上的高密度区域。",
    "unsupervisedGuide",
  ],
  [
    "hierarchical",
    "层次聚类",
    "通过合并或分裂形成多级簇结构。",
    "想观察群体的多层关系。",
    "距离与连接方式会改变树形结果。",
    "用树状图观察产品分组层级。",
    "unsupervisedGuide",
  ],
  [
    "pca-method",
    "PCA 线性降维",
    "寻找最大方差的正交线性方向。",
    "压缩相关数值特征。",
    "大方差方向不一定最有预测价值。",
    "只在训练折拟合 PCA 后验证。",
    "unsupervisedGuide",
  ],
  [
    "umap",
    "UMAP / t-SNE",
    "将高维邻域关系映射到低维。",
    "探索嵌入与局部结构。",
    "二维图距离不能简单代表全部原空间关系。",
    "观察文本嵌入的邻域分布。",
    "umap",
  ],
  [
    "gmm",
    "高斯混合模型 GMM",
    "用多个高斯分量表示概率密度。",
    "软聚类或近似多峰连续分布。",
    "分量形状与数量是建模假设。",
    "给样本分配属于各簇的概率。",
    "unsupervisedGuide",
  ],
  [
    "kde",
    "核密度估计 KDE",
    "用局部核函数平滑估计密度。",
    "低维连续数据分布探索。",
    "带宽选择和高维稀疏影响很大。",
    "绘制一维消费金额的平滑密度。",
    "unsupervisedGuide",
  ],
  [
    "isolation",
    "Isolation Forest",
    "通过随机划分隔离异常点。",
    "较少标签的数值异常筛查。",
    "异常分数不等于欺诈概率。",
    "挑出需要人工核查的交易。",
    "unsupervisedGuide",
  ],
  [
    "masked",
    "掩码预测",
    "隐藏部分输入，再让模型恢复。",
    "自监督学习图像或文本表示。",
    "掩码任务必须与目标表示需求相关。",
    "遮住文本中的词再预测。",
    "d2l",
  ],
  [
    "autoregressive",
    "自回归预测",
    "根据先前部分预测下一部分。",
    "语言生成或序列预训练。",
    "训练时可见范围不能穿越目标位置。",
    "根据前文预测下一个 token。",
    "hf",
  ],
  [
    "label-propagation",
    "标签传播",
    "沿样本相似关系传播少量标签。",
    "邻近样本倾向同类且标签稀缺。",
    "错误相似度会传播错误标签。",
    "在相似用户图上传播已知类别。",
    "sklearn",
  ],
  [
    "consistency",
    "一致性正则化",
    "鼓励扰动前后的预测保持合理一致。",
    "有相关无标签数据且扰动保留语义。",
    "扰动改变真实标签时会误导模型。",
    "同一图像不同增强应预测一致。",
    "d2l",
  ],
  [
    "policy-gradient",
    "REINFORCE",
    "直接根据回报调整策略概率。",
    "理解策略梯度和离散或连续策略。",
    "回报方差高，通常需要方差缩减。",
    "增加高回报轨迹中动作的概率。",
    "rlTree",
  ],
  [
    "a2c",
    "A2C / Actor-Critic",
    "策略负责动作，价值估计辅助更新策略。",
    "理解结合策略与价值的 RL 方法。",
    "价值估计偏差与交互预算都影响训练。",
    "用价值基线减少策略梯度波动。",
    "rlTree",
  ],
  [
    "world-model",
    "世界模型 / 模型式 RL",
    "学习或利用环境模型做规划或策略改进。",
    "有模型可用或交互成本高。",
    "模型误差会在多步规划中累积。",
    "在学到的动力学中比较候选动作序列。",
    "rlTree",
  ],
  [
    "ridge",
    "Ridge · L2 正则",
    "惩罚系数平方，缩小不稳定权重。",
    "相关特征或需要稳定线性回归。",
    "需匹配特征尺度。",
    "交叉验证选择正则强度。",
    "supervisedGuide",
  ],
  [
    "lasso",
    "Lasso / Elastic Net",
    "用 L1 或混合惩罚产生稀疏系数。",
    "希望压缩特征或获得稀疏模型。",
    "相关特征下选择结果可能不稳定。",
    "比较稀疏性与预测误差。",
    "supervisedGuide",
  ],
  [
    "decision-tree",
    "决策树 CART",
    "递归划分特征空间形成预测规则。",
    "需要非线性与可读分割基线。",
    "深树容易过拟合，小扰动可能改变结构。",
    "限制树深预测用户流失。",
    "supervisedGuide",
  ],
  [
    "knn",
    "K 近邻 KNN",
    "依据相似样本的目标进行预测。",
    "中小数据、相似度有意义。",
    "高维、尺度差异和推理成本要注意。",
    "标准化后让最近邻投票。",
    "supervisedGuide",
  ],
  [
    "naive-bayes",
    "朴素贝叶斯",
    "在条件独立假设下组合特征证据。",
    "稀疏文本的快速概率基线。",
    "条件独立假设不一定成立，概率需检查。",
    "用词频判断文本类别。",
    "supervisedGuide",
  ],
  [
    "sgd",
    "SGD / Momentum",
    "用小批梯度更新；动量累积更新方向。",
    "神经网络的基础优化方法。",
    "学习率和调度对效果影响明显。",
    "比较带动量 SGD 与 AdamW。",
    "optim",
  ],
  [
    "adam",
    "Adam",
    "按梯度的一阶与二阶矩调整更新尺度。",
    "需要自适应学习率的神经训练。",
    "与 AdamW 的权重衰减实现有区别。",
    "以 Adam 建立小网络训练基线。",
    "optim",
  ],
  [
    "adamw-method",
    "AdamW",
    "将权重衰减与自适应梯度更新解耦。",
    "预训练网络微调的候选优化器。",
    "仍需调学习率和衰减强度。",
    "配合 warmup 微调 Transformer。",
    "optim",
  ],
  [
    "step-lr",
    "阶梯 / 指数衰减",
    "按固定节点或比例降低学习率。",
    "预先知道训练阶段安排。",
    "固定计划不感知验证表现。",
    "每若干轮降低一次学习率。",
    "optim",
  ],
  [
    "plateau",
    "ReduceLROnPlateau",
    "根据监测指标停滞情况降低学习率。",
    "希望按训练反馈调节学习率。",
    "噪声大时需要合理容忍与等待。",
    "验证损失持续不降时调小步长。",
    "optim",
  ],
  [
    "onecycle",
    "OneCycle",
    "按一个周期先升后降学习率。",
    "固定预算下尝试快速训练方案。",
    "峰值学习率过大可能发散。",
    "在同一预算内与余弦调度比较。",
    "optim",
  ],
  [
    "weight-decay",
    "权重衰减",
    "对权重施加收缩以约束复杂度。",
    "模型过拟合或权重需要控制。",
    "与某些优化器的 L2 惩罚并不等同。",
    "在 AdamW 中调 weight_decay。",
    "optim",
  ],
  [
    "dropout",
    "Dropout",
    "训练时随机屏蔽部分激活。",
    "部分神经网络存在过拟合。",
    "训练和推理模式行为不同。",
    "在 MLP 隐层使用适度 Dropout。",
    "d2l",
  ],
  [
    "cross-entropy",
    "交叉熵损失",
    "惩罚对真实类别分配较低概率。",
    "训练分类网络。",
    "需确认输入为 logits 还是概率。",
    "用交叉熵训练多分类器。",
    "d2l",
  ],
  [
    "regression-loss",
    "MSE / MAE / Huber",
    "以不同方式衡量连续目标预测误差。",
    "根据异常值与业务代价选择回归目标。",
    "训练损失与最终评分未必一致。",
    "异常值多时比较 Huber 与 MSE。",
    "d2l",
  ],
  [
    "focal",
    "Focal loss / 类别加权",
    "改变不同类别或困难样本的训练权重。",
    "类别不平衡或易样本占比过高。",
    "可能影响概率校准，并非必定提升。",
    "比较加权损失与原始交叉熵。",
    "d2l",
  ],
  [
    "platt",
    "Platt / Isotonic 校准",
    "用 sigmoid 或单调映射调整概率。",
    "传统模型的概率校准候选。",
    "校准集小的时候复杂映射易过拟合。",
    "比较独立数据上的 Brier 分数。",
    "calibration",
  ],
  [
    "bagging",
    "Bagging / 平均融合",
    "对多个模型预测做平均或投票。",
    "基模型误差有差异。",
    "高度相同的模型收益可能有限。",
    "平均多个随机种子的概率。",
    "sklearn",
  ],
  [
    "stacking-method",
    "Stacking · 二层融合",
    "用基模型的折外预测训练融合器。",
    "有互补模型且验证样本足够。",
    "训练内预测会向融合器泄漏。",
    "用 OOF 概率训练逻辑回归融合器。",
    "sklearn",
  ],
  [
    "feature-select",
    "过滤 / 包装 / 嵌入式选择",
    "分别按统计、搜索或模型训练选择特征。",
    "特征噪声多或计算成本高。",
    "选择过程也必须放进训练折。",
    "比较移除无效特征后的验证表现。",
    "sklearn",
  ],
  [
    "imputation",
    "均值 / 中位数 / 模型填补",
    "用简单统计或预测方式填补缺失值。",
    "模型无法直接处理缺失。",
    "填补参数不能从测试数据学习。",
    "训练折中位数填补年龄。",
    "sklearn",
  ],
  [
    "onehot",
    "One-hot 编码",
    "把类别展开成多个二元列。",
    "类别数不高或线性模型处理类别。",
    "高基数会造成宽而稀疏的矩阵。",
    "为渠道编码后训练逻辑回归。",
    "sklearn",
  ],
  [
    "random-split",
    "随机 / 分层切分",
    "随机划分样本，分层可保持类别比例。",
    "样本近似独立同分布。",
    "时间依赖或重复实体应换验证方式。",
    "分类任务用分层 K 折。",
    "validation",
  ],
  [
    "resnet",
    "ResNet · 残差网络",
    "通过残差连接帮助训练较深卷积网络。",
    "视觉分类或特征提取。",
    "结构有效不代表需要从零训练。",
    "微调已有 ResNet 权重。",
    "d2l",
  ],
  [
    "unet",
    "U-Net · 编解码与跳连",
    "结合多尺度编码解码与跳跃连接。",
    "像素级分割或生成模型中的网络组件。",
    "分类任务未必需要输出密集像素图。",
    "进行图像分割。",
    "d2l",
  ],
  [
    "encoder",
    "编码器 · BERT 类",
    "以双向上下文编码输入表示。",
    "分类、抽取、表示学习。",
    "通常不能直接按自回归方式生成长回答。",
    "对文本编码后接分类头。",
    "hf",
  ],
  [
    "decoder",
    "解码器 · GPT 类",
    "以因果注意力处理和生成序列。",
    "文本生成、指令任务。",
    "长输入与生成长度影响资源。",
    "根据提示生成回答。",
    "hf",
  ],
  [
    "encoder-decoder",
    "编码器—解码器 · T5 类",
    "先编码输入，再条件生成输出。",
    "翻译、摘要等序列到序列任务。",
    "需要匹配模型预训练与任务格式。",
    "输入文章生成摘要。",
    "hf",
  ],
  [
    "vit",
    "ViT · 视觉 Transformer",
    "将图像块作为 token 处理。",
    "视觉表征与分类。",
    "小数据优先比较预训练微调。",
    "对图像块序列进行分类。",
    "hf",
  ],
  [
    "lora-method",
    "LoRA 低秩适配",
    "只学习权重更新中的低秩部分。",
    "全量微调过于昂贵。",
    "秩与目标层的选择需验证。",
    "在注意力投影层加入适配器。",
    "peft",
  ],
  [
    "qlora",
    "QLoRA",
    "量化基础权重并训练低秩适配器。",
    "显存紧张的大模型微调。",
    "量化支持和数值精度必须检查。",
    "用低比特基础权重配合 LoRA。",
    "peft",
  ],
  [
    "chunking",
    "文档切分与索引",
    "把文档切为可检索单元并保留元数据。",
    "搭建文档检索系统。",
    "切断语义或丢掉出处会妨碍回答。",
    "按章节切分并保存文档位置。",
    "rag",
  ],
  [
    "rag-eval",
    "检索召回与忠实性",
    "分别评估找没找到证据和回答是否受证据支持。",
    "迭代 RAG 链路。",
    "流畅回答不等于检索正确。",
    "单独记录证据召回与答案支持率。",
    "rag",
  ],
  [
    "quantization",
    "模型量化",
    "用更少比特表示权重或激活以降低成本。",
    "部署受内存、延迟限制。",
    "须比较精度、兼容性和实际速度。",
    "比较量化前后的任务指标。",
    "peft",
  ],
  [
    "distillation",
    "知识蒸馏",
    "用教师模型信号训练较小学生模型。",
    "希望保留能力但降低推理成本。",
    "教师错误也可能传给学生。",
    "用软标签训练小分类网络。",
    "d2l",
  ],
  [
    "batch-service",
    "批量预测 / 在线服务",
    "按周期批处理或按请求实时预测。",
    "交付模型供业务使用。",
    "延迟、吞吐与失败处理需求不同。",
    "每天批量生成用户流失分数。",
    "mlflow",
  ],
  [
    "ci",
    "自动化检查与持续集成",
    "提交改动后自动执行必要验证。",
    "多人协作或重复发布。",
    "测试通过不代表业务效果可靠。",
    "自动检查特征输入与推理接口。",
    "git",
  ],
  [
    "data-version",
    "数据与模型版本",
    "记录训练数据快照、模型与依赖关系。",
    "需要复现结果或回滚。",
    "只保存模型而没有数据口径不够。",
    "给数据快照和模型记录版本号。",
    "mlflow",
  ],
];
rows.push(
  [
    "sarsa",
    "SARSA",
    "以当前行为策略的下一动作价值更新动作价值。",
    "理解同策略价值学习。",
    "探索行为会直接影响更新目标。",
    "在网格世界比较 SARSA 与 Q-learning。",
    "sutton",
  ],
  [
    "q-table",
    "表格 Q-learning",
    "用下一状态的最大动作价值构造更新目标。",
    "离散且规模很小的状态动作空间。",
    "不能直接扩展到高维连续状态。",
    "在小环境维护一张动作价值表。",
    "sutton",
  ],
  [
    "sac-method",
    "SAC",
    "加入熵目标的离策略 Actor-Critic 方法。",
    "连续控制，希望复用交互数据。",
    "熵系数、数据质量与动作缩放需要检查。",
    "比较同一模拟器中的回报与交互成本。",
    "rl",
  ],
  [
    "td3",
    "TD3",
    "结合双价值估计和延迟策略更新的连续控制方法。",
    "连续动作的离策略候选算法。",
    "探索与超参数仍需按环境评估。",
    "与 SAC 在相同预算下比较。",
    "rl",
  ],
  [
    "cql-method",
    "CQL",
    "约束离线动作价值高估的保守学习方法。",
    "只有历史交互数据时。",
    "保守程度与数据覆盖会影响策略。",
    "在固定离线轨迹上训练并独立评估。",
    "cql",
  ],
  [
    "iql-method",
    "IQL",
    "通过隐式价值学习和优势加权提取离线策略。",
    "离线强化学习候选方案。",
    "不能绕过历史数据覆盖和离线评估问题。",
    "与行为克隆和 CQL 做比较。",
    "iql",
  ],
  [
    "vanilla-rnn",
    "基础 RNN",
    "用递归隐藏状态处理序列。",
    "理解循环网络基本机制。",
    "长依赖可能出现梯度问题。",
    "用小序列观察隐藏状态更新。",
    "d2l",
  ],
  [
    "lstm",
    "LSTM",
    "通过输入、遗忘和输出门调节记忆。",
    "循环序列建模的候选结构。",
    "不是所有序列任务的默认最优选择。",
    "在时间序列上与简单基线比较。",
    "d2l",
  ],
  [
    "gru",
    "GRU",
    "用门控机制更新递归隐藏状态。",
    "希望使用相对简洁的门控循环网络。",
    "效果与成本仍需实际比较。",
    "在流式序列上训练小型 GRU。",
    "d2l",
  ],
  [
    "seasonal-naive",
    "朴素 / 季节基线",
    "复用最近值或上一季节对应值预测未来。",
    "时间序列的必要低成本参照。",
    "结构变化后可能失效。",
    "用上周同期销量预测本周。",
    "timeseries",
  ],
  [
    "arima",
    "ARIMA / SARIMA",
    "以自回归、差分与移动平均建模时间依赖。",
    "存在适配的线性或季节结构。",
    "检查平稳性、残差与预测跨度。",
    "滚动回测比较季节 ARIMA。",
    "timeseries",
  ],
  [
    "ets",
    "指数平滑 ETS",
    "以递减权重更新水平、趋势与季节成分。",
    "趋势或季节性较明确的序列。",
    "结构突变与复杂外部变量需要额外考虑。",
    "比较不同季节平滑方案。",
    "timeseries",
  ],
  [
    "gcn",
    "GCN",
    "根据邻接关系聚合节点特征。",
    "图上节点表示或预测。",
    "过多层可能过度平滑；图划分也有泄漏风险。",
    "在引文图上学习节点表示。",
    "d2l",
  ],
  [
    "gat",
    "GAT",
    "以注意力给邻居信息不同权重。",
    "邻居贡献差异可能重要。",
    "注意力权重不直接等于因果解释。",
    "比较有无注意力的图聚合。",
    "d2l",
  ],
  [
    "graphsage",
    "GraphSAGE",
    "采样并聚合邻居以学习节点表示。",
    "图规模较大或需要处理新节点。",
    "采样预算会影响表示质量。",
    "用局部邻居样本学习用户节点表示。",
    "d2l",
  ],
  [
    "ddpm",
    "扩散去噪 DDPM 类",
    "通过逐步去噪学习生成样本。",
    "图像等生成任务。",
    "采样成本和训练数据需要匹配。",
    "使用预训练扩散模型生成图像。",
    "diffusion",
  ],
  [
    "flow-matching",
    "流匹配 Flow matching",
    "学习连接简单分布与数据分布的速度场。",
    "连续生成建模的候选路线。",
    "具体路径和数值采样影响表现。",
    "使用支持流匹配的预训练模型。",
    "diffusion",
  ],
);
rows.forEach((r) => add(...r));

// B 创建导航分支；复用旧 id 时保留详细知识笔记。树边表示导航包含，不宣称学术互斥。
function B(id, title, children, what, when, source = "sklearn") {
  if (!catalog.has(id))
    add(
      id,
      title,
      what,
      when,
      "子分支是组织这一问题的常用维度；方法可能跨分支使用。",
      `从${children
        .map(
          (c) => catalog.get(typeof c === "string" ? c : c.id)?.title || c.id,
        )
        .slice(0, 3)
        .join("、")}中找到对应入口。`,
      source,
    );
  else if (title) catalog.get(id).title = title;
  return {
    id,
    children: children.map((c) =>
      typeof c === "string" ? { id: c, children: [] } : c,
    ),
  };
}
const foundation = B(
  "foundation",
  "基础工具与数学",
  [
    B(
      "programming",
      "编程与数据工具",
      [
        B("python", null, ["python-syntax", "functions"]),
        B("sql", null, ["sql-join", "sql-window"]),
        "duckdb",
        "visual",
      ],
      "操作数据所需的语言与工具。",
      "开始取数、清洗和分析时。",
      "pythonGuide",
    ),
    B(
      "math-tree",
      "数学基础",
      [
        B("probability", null, ["bayes", "distributions"]),
        B("linear-algebra", null, ["matrix", "eigen"]),
        "gradient",
      ],
      "用概率、代数和梯度理解模型。",
      "需要读懂具体建模机制时。",
      "d2l",
    ),
    B(
      "statistics",
      "统计基础",
      ["uncertainty", "bootstrap", "hypothesis", "power"],
      "从样本推断总体并表达不确定性。",
      "比较群体、设计实验或评估差异。",
      "stats",
    ),
  ],
  "数据与模型的基础语言。",
  "其他知识的前置支撑。",
  "d2l",
);
const analysis = B(
  "analysis",
  "业务分析与因果",
  [
    B(
      "business-description",
      "描述与诊断",
      [B("metrics", null, ["funnel", "cohort"]), "eda"],
      "先建立口径，再分群与拆解。",
      "回答发生了什么、变化集中在哪里。",
      "stats",
    ),
    B(
      "experiments",
      "实验分析",
      [B("ab", null, ["cuped"])],
      "通过随机实验识别干预效果。",
      "能控制干预分配时。",
      "cuped",
    ),
    B("causal", null, ["dag", "did", "matching", "instrument", "rdd"]),
  ],
  "描述、实验与观测因果推断的组织树。",
  "处理业务问题时。",
  "causal",
);
const learning = B(
  "learning",
  "学习方式",
  [
    B("supervised", null, [
      B(
        "classification",
        "分类任务",
        ["binary", "multiclass", "multilabel"],
        "预测离散标签，按标签结构继续细分。",
        "需要判断类别时。",
        "supervisedGuide",
      ),
      B(
        "regression",
        "回归任务",
        ["point-regression", "quantile"],
        "预测连续目标或条件分位数。",
        "价格、需求、时长等数值预测。",
        "supervisedGuide",
      ),
      "ranking",
    ]),
    B("unsupervised", null, [
      B(
        "kmeans",
        "聚类",
        ["kmeans-method", "dbscan", "hierarchical"],
        "按距离、密度或层次发现群体。",
        "没有目标标签但希望理解群体结构。",
        "unsupervisedGuide",
      ),
      B(
        "pca",
        "降维与表示压缩",
        ["pca-method", "umap"],
        "将高维信息表示到更低维。",
        "压缩或探索结构。",
        "unsupervisedGuide",
      ),
      B(
        "density",
        "密度估计",
        ["gmm", "kde"],
        "建模数据分布而非目标标签。",
        "估计概率密度或软群体。",
        "unsupervisedGuide",
      ),
      B("anomaly", null, ["isolation"]),
    ]),
    B("self-supervised", null, ["masked", "autoregressive", "contrastive"]),
    B("semi-supervised", null, ["pseudo", "label-propagation", "consistency"]),
    B("rl", null, [
      B(
        "model-free",
        "无模型强化学习",
        [
          B(
            "value-based",
            "价值方法",
            [B("qlearning", "表格价值学习", ["q-table", "sarsa"]), "dqn"],
            "学习动作价值再选动作。",
            "适合从价值估计理解策略。",
            "rlTree",
          ),
          B(
            "policy-based",
            "策略与 Actor-Critic",
            [
              "policy-gradient",
              "a2c",
              "ppo",
              B("sac", "SAC / TD3", ["sac-method", "td3"]),
            ],
            "直接学习策略，常配合价值估计。",
            "离散或连续控制，按预算选算法。",
            "rlTree",
          ),
        ],
        "不显式构造环境动力学来规划。",
        "可以从交互经验学习时。",
        "rlTree",
      ),
      "world-model",
      B("offline-rl", null, ["cql-method", "iql-method"]),
    ]),
    "bandit",
  ],
  "按反馈来源理解学习方式；任务与算法用跨树关系连接。",
  "先判断你有什么反馈，再找方法。",
  "sklearn",
);
const models = B(
  "models",
  "模型与任务",
  [
    B(
      "classic-models",
      "经典模型家族",
      [
        B(
          "linear-family",
          "线性与广义线性",
          [B("linear", "线性回归与正则化", ["ridge", "lasso"]), "logistic"],
          "以线性得分描述输入输出关系。",
          "低成本、稀疏或可解释基线。",
          "supervisedGuide",
        ),
        B(
          "tree-models",
          "树与提升模型",
          [
            "decision-tree",
            "random-forest",
            B("gbdt", null, ["lightgbm", "xgboost", "catboost"]),
          ],
          "用分割规则及其集成建模。",
          "非线性表格预测。",
          "supervisedGuide",
        ),
        B(
          "similarity-models",
          "邻近、核与概率模型",
          ["svm", "knn", "naive-bayes"],
          "用距离、核相似度或概率假设建模。",
          "模型假设适合特征结构时。",
          "supervisedGuide",
        ),
      ],
      "按模型机制组织具体算法。",
      "选预测基线时。",
      "supervisedGuide",
    ),
    B("deep-learning", null, [
      "mlp",
      B("cnn", null, ["resnet", "unet"]),
      B("transformer", null, ["encoder", "decoder", "encoder-decoder", "vit"]),
      B("rnn", "循环网络 RNN", ["vanilla-rnn", "lstm", "gru"]),
      B("gnn", null, ["gcn", "gat", "graphsage"]),
    ]),
    B("time-series", null, ["seasonal-naive", "arima", "ets"]),
    "tabpfn",
  ],
  "模型按机制组织，与分类、回归等任务多对多关联。",
  "同一任务往往有多个候选家族。",
  "sklearn",
);
const workflow = B(
  "workflow",
  "验证与特征",
  [
    B("validation", null, [
      "random-split",
      "group-split",
      "time-split",
      "leakage",
    ]),
    B(
      "features-tree",
      "特征工程",
      [
        B("missing", null, ["imputation"]),
        B(
          "encoding",
          "特征编码",
          ["onehot", "target-encoding", "tfidf"],
          "把原始字段表示为模型可用的输入。",
          "原始类型与模型输入不一致时。",
          "sklearn",
        ),
        "scaling",
        "lag",
        "feature-select",
      ],
      "从清洗到表达，再选择有效信息。",
      "想提高有效信号而不是只换模型时。",
      "sklearn",
    ),
    B(
      "evaluation-tree",
      "评估与实验迭代",
      ["scoring", "error-analysis", "shap", "optuna"],
      "比较指标、分析错误并迭代方案。",
      "有可靠验证后寻找改进。",
      "validation",
    ),
  ],
  "从可信验证到信息构造。",
  "所有建模方案都依赖这一流程。",
  "validation",
);
const toolbox = B(
  "toolbox",
  "训练与后处理",
  [
    B(
      "losses",
      "训练目标与损失",
      ["cross-entropy", "regression-loss", "focal"],
      "决定训练怎样惩罚错误。",
      "目标、数据不平衡或错判代价不同。",
      "d2l",
    ),
    B(
      "training-optimization",
      "优化训练",
      [
        B("adamw", "优化器", ["sgd", "adam", "adamw-method"]),
        B(
          "schedules",
          "学习率调度",
          ["warmup", "cosine", "step-lr", "plateau", "onecycle"],
          "安排每一步学习率。",
          "在固定预算下改善优化过程。",
          "optim",
        ),
        "gradient-clip",
        "early-stop",
      ],
      "让模型更稳定地优化训练目标。",
      "神经网络训练与模型迭代。",
      "optim",
    ),
    B(
      "generalize",
      "泛化与效率",
      [
        B("regularization", "正则化", ["weight-decay", "dropout"]),
        "augmentation",
        "amp",
        "ema",
      ],
      "控制过拟合与计算成本。",
      "训练与验证有差距或资源有限。",
      "d2l",
    ),
    B(
      "post-tree",
      "预测后处理",
      [
        B("calibration", null, ["temperature", "platt"]),
        "threshold",
        B("ensemble", null, ["bagging", "stacking-method"]),
        "conformal",
      ],
      "调整概率、决策或多个模型的输出。",
      "模型训练完后，按目标解决剩余问题。",
      "calibration",
    ),
  ],
  "技巧按作用阶段组织，可跨模型组合。",
  "需要明确技巧解决哪个训练或预测问题时。",
  "tuning",
);
const modern = B(
  "modern",
  "基础模型与生成式 AI",
  [
    B("pretrained", null, [
      "embeddings",
      "multimodal",
      B("diffusion", "扩散与流匹配", ["ddpm", "flow-matching"]),
    ]),
    B(
      "adaptation-tree",
      "模型适配",
      [
        B("lora", "参数高效微调", ["lora-method", "qlora"]),
        "sft",
        B(
          "posttraining-tree",
          "偏好与奖励后训练",
          ["dpo", "grpo"],
          "按偏好对或可计算奖励适配生成行为。",
          "有相应反馈且基础评估已建立。",
          "dpo",
        ),
      ],
      "根据任务和预算适配预训练模型。",
      "已有模型但行为不符合任务。",
      "peft",
    ),
    B("rag", null, ["chunking", "rerank", "rag-eval"]),
    B(
      "system-tree",
      "应用与效率",
      ["agent", "llm-eval", "quantization", "distillation"],
      "把模型组成可评估的应用。",
      "需要工具、资源优化或交付。",
      "hf",
    ),
  ],
  "从复用表示，到检索、适配和应用。",
  "使用现代预训练模型解决实际问题。",
  "hf",
);
const engineering = B(
  "engineering",
  "工程与交付",
  [
    B(
      "reproducibility",
      "复现与协作",
      ["git", "tracking", "data-version", "ci"],
      "记录变化和产物，建立重复运行的流程。",
      "需要协作与复现。",
      "git",
    ),
    B("deployment", null, ["batch-service", "drift"]),
    B(
      "scale-engineering",
      "数据规模与计算",
      ["distributed"],
      "按规模选择计算架构。",
      "单机工作流确实无法满足需求。",
      "spark",
    ),
  ],
  "让学习成果变成可重复使用的产物。",
  "开始交付模型或分析。",
  "mlflow",
);
export const tree = B(
  "universe",
  "数据与 AI 知识宇宙",
  [
    foundation,
    analysis,
    learning,
    models,
    workflow,
    toolbox,
    modern,
    engineering,
  ],
  "一张包含知识层级和跨领域关系的地图。",
  "先看全貌，再放大具体子树。",
  "sklearn",
);
catalog.get("rl").avoid =
  "普通固定数据预测题通常不需要 RL。无模型 / 模型式按是否使用环境模型区分；离线 / 在线按数据获取方式区分，这两种维度可以交叉。";
expandUniverse(tree, catalog, add, paths, recipes);
const records = [];
export const hierarchy = [];
function visit(t, parent = null, domain = null, depth = 0) {
  const n = catalog.get(t.id);
  if (!n) throw Error("Missing " + t.id);
  if (records.some((x) => x.id === t.id))
    throw Error("Repeated tree node " + t.id);
  const own = depth === 1 ? t.id : domain;
  records.push({
    ...n,
    parent,
    domain: own,
    depth,
    children: t.children.map((c) => c.id),
    section: "universe",
    reviewed: n.reviewed || reviewed,
  });
  if (parent)
    hierarchy.push({
      source: parent,
      target: t.id,
      type: "contains",
      label: "包含",
    });
  t.children.forEach((c) => visit(c, t.id, own, depth + 1));
}
visit(tree);
export const nodes = records;
export const nodeMap = new Map(nodes.map((n) => [n.id, n]));
for (const n of original)
  if (!nodeMap.has(n.id))
    throw Error("Original note missing from connected tree: " + n.id);
export const relationTypes = {
  applies: { label: "适用", color: "#83b9ff", dash: "7 5" },
  requires: { label: "依赖", color: "#e1bf79", dash: "2 5" },
  combines: { label: "可组合", color: "#d89bfd", dash: "10 4 2 4" },
  contrasts: { label: "对照", color: "#99b2c5", dash: "5 6" },
};
// 方向明确：方法 → 适用任务；概念 → 前置；组合与对照是对称关系。
export const relations = [
  ...expansionRelations,
  ["logistic", "binary", "applies"],
  ["logistic", "multiclass", "applies"],
  ["gbdt", "classification", "applies"],
  ["gbdt", "regression", "applies"],
  ["linear", "point-regression", "applies"],
  ["quantile", "conformal", "contrasts"],
  ["knn", "classification", "applies"],
  ["knn", "regression", "applies"],
  ["naive-bayes", "classification", "applies"],
  ["cnn", "classification", "applies"],
  ["unet", "augmentation", "combines"],
  ["ranking", "xgboost", "combines"],
  ["gmm", "kmeans", "applies"],
  ["deep-learning", "supervised", "applies"],
  ["deep-learning", "self-supervised", "applies"],
  ["deep-learning", "rl", "applies"],
  ["tabpfn", "supervised", "applies"],
  ["transformer", "masked", "combines"],
  ["decoder", "autoregressive", "combines"],
  ["embeddings", "contrastive", "combines"],
  ["dqn", "deep-learning", "requires"],
  ["rl", "probability", "requires"],
  ["pca-method", "eigen", "requires"],
  ["svm", "scaling", "requires"],
  ["kmeans-method", "scaling", "combines"],
  ["ab", "power", "requires"],
  ["ab", "hypothesis", "combines"],
  ["ab", "uncertainty", "requires"],
  ["causal", "dag", "requires"],
  ["lag", "time-split", "requires"],
  ["time-series", "lag", "combines"],
  ["catboost", "target-encoding", "contrasts"],
  ["stacking-method", "validation", "requires"],
  ["temperature", "validation", "requires"],
  ["cnn", "cosine", "combines"],
  ["transformer", "warmup", "combines"],
  ["adamw-method", "cosine", "combines"],
  ["adamw-method", "weight-decay", "combines"],
  ["cnn", "augmentation", "combines"],
  ["lora-method", "sft", "combines"],
  ["qlora", "quantization", "requires"],
  ["sft", "supervised", "applies"],
  ["grpo", "rl", "applies"],
  ["dpo", "grpo", "contrasts"],
  ["ppo", "grpo", "contrasts"],
  ["rag", "embeddings", "combines"],
  ["rag", "llm-eval", "requires"],
  ["agent", "rl", "contrasts"],
  ["diffusion", "lora-method", "combines"],
  ["conformal", "validation", "requires"],
  ["threshold", "calibration", "contrasts"],
  ["scoring", "cross-entropy", "contrasts"],
  ["python", "tracking", "combines"],
  ["distributed", "duckdb", "contrasts"],
  ["deployment", "data-version", "requires"],
].map(([source, target, type], i) => ({
  id: `r${i}`,
  source,
  target,
  type,
  label: relationTypes[type].label,
}));
export function ancestors(id) {
  const result = [];
  for (let n = nodeMap.get(id); n; n = nodeMap.get(n.parent)) result.unshift(n);
  return result;
}
export function descendants(id) {
  const result = [];
  function walk(key) {
    const n = nodeMap.get(key);
    result.push(n);
    n.children.forEach(walk);
  }
  walk(id);
  return result;
}
export function neighborhood(id) {
  return relations.filter((r) => r.source === id || r.target === id);
}
